name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test --info --stacktrace

    - name: Upload test failure report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-failure-report
        path: app/build/reports/tests/testDebugUnitTest/failed-tests/
